STRINGS.NAMES.LAVA_POND = "Magma"
STRINGS.NAMES.LAVA_POND_ROCK = "Rock"
STRINGS.NAMES.SCORCHED_SKELETON = "Crispy Skeleton"
STRINGS.NAMES.BURNT_MARSH_BUSH = "Spiky Bush"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCORCHED_SKELETON = "Spooky."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURNT_MARSH_BUSH = "It's all burnt up."