STRINGS.NAMES.ROCK_MOON = "Boulder"
STRINGS.NAMES.WALL_MOONROCK_ITEM = "Moon Rock Wall"
STRINGS.NAMES.WALL_MOONROCK = "Moon Rock Wall"
STRINGS.NAMES.MOONROCKNUGGET = "Moon Rock"

STRINGS.RECIPE_DESC.WALL_MOONROCK_ITEM = "Walls for the lunar looney."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONROCKNUGGET = "That rock came from the moon."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_MOONROCK = "Spacey and smooth!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_MOONROCK_ITEM = "Very light but surprisingly tough."