local seg_time = 30
local total_day_time = seg_time*16

TUNING.METEOR_DAMAGE = 50
TUNING.METEOR_RADIUS = 3.5
TUNING.METEOR_SMASH_INVITEM_CHANCE = .75

TUNING.METEOR_MEDIUM_CHANCE = .2
TUNING.METEOR_LARGE_CHANCE = .2

TUNING.METEOR_CHANCE_INVITEM_ALWAYS = 1
TUNING.METEOR_CHANCE_INVITEM_OFTEN = .6
TUNING.METEOR_CHANCE_INVITEM_SOMETIMES = .4
TUNING.METEOR_CHANCE_INVITEM_OCCASIONAL = .3
TUNING.METEOR_CHANCE_INVITEM_RARE = .2
TUNING.METEOR_CHANCE_INVITEM_VERYRARE = .12
TUNING.METEOR_CHANCE_INVITEM_SUPERRARE = .05

TUNING.METEOR_CHANCE_BOULDERROCK = 1
TUNING.METEOR_CHANCE_BOULDERFLINTLESS = .3
TUNING.METEOR_CHANCE_BOULDERMOON = .1

TUNING.METEOR_SHOWER_SPAWN_RADIUS= 60

TUNING.METEOR_SHOWER_OFFSCREEN_MOD = .5

TUNING.METEOR_SHOWER_LVL1_BASETIME = total_day_time*6
TUNING.METEOR_SHOWER_LVL1_VARTIME = total_day_time*4
TUNING.METEOR_SHOWER_LVL2_BASETIME = total_day_time*9
TUNING.METEOR_SHOWER_LVL2_VARTIME = total_day_time*6
TUNING.METEOR_SHOWER_LVL3_BASETIME = total_day_time*12
TUNING.METEOR_SHOWER_LVL3_VARTIME = total_day_time*8

TUNING.METEOR_SHOWER_LVL1_DURATION_BASE = 5
TUNING.METEOR_SHOWER_LVL1_DURATIONVAR_MIN = 5
TUNING.METEOR_SHOWER_LVL1_DURATIONVAR_MAX = 10
TUNING.METEOR_SHOWER_LVL1_METEORSPERSEC_MIN = 2
TUNING.METEOR_SHOWER_LVL1_METEORSPERSEC_MAX = 4
TUNING.METEOR_SHOWER_LVL1_MEDMETEORS_MIN = 1
TUNING.METEOR_SHOWER_LVL1_MEDMETEORS_MAX = 3
TUNING.METEOR_SHOWER_LVL1_LRGMETEORS_MIN = 1
TUNING.METEOR_SHOWER_LVL1_LRGMETEORS_MAX = 4

TUNING.METEOR_SHOWER_LVL2_DURATION_BASE = 5
TUNING.METEOR_SHOWER_LVL2_DURATIONVAR_MIN = 10
TUNING.METEOR_SHOWER_LVL2_DURATIONVAR_MAX = 20
TUNING.METEOR_SHOWER_LVL2_METEORSPERSEC_MIN = 3
TUNING.METEOR_SHOWER_LVL2_METEORSPERSEC_MAX = 7
TUNING.METEOR_SHOWER_LVL2_MEDMETEORS_MIN = 2
TUNING.METEOR_SHOWER_LVL2_MEDMETEORS_MAX = 4
TUNING.METEOR_SHOWER_LVL2_LRGMETEORS_MIN = 2
TUNING.METEOR_SHOWER_LVL2_LRGMETEORS_MAX = 7

TUNING.METEOR_SHOWER_LVL3_DURATION_BASE = 5
TUNING.METEOR_SHOWER_LVL3_DURATIONVAR_MIN = 15
TUNING.METEOR_SHOWER_LVL3_DURATIONVAR_MAX = 30
TUNING.METEOR_SHOWER_LVL3_METEORSPERSEC_MIN = 4
TUNING.METEOR_SHOWER_LVL3_METEORSPERSEC_MAX = 10
TUNING.METEOR_SHOWER_LVL3_MEDMETEORS_MIN = 3
TUNING.METEOR_SHOWER_LVL3_MEDMETEORS_MAX = 6
TUNING.METEOR_SHOWER_LVL3_LRGMETEORS_MIN = 3
TUNING.METEOR_SHOWER_LVL3_LRGMETEORS_MAX = 10

TUNING.MOONROCKWALL_HEALTH = 600
TUNING.MOONROCKWALL_PLAYERDAMAGEMOD = .25
TUNING.MOONROCKWALL_WORK = 25