local function OverrideTuningVariables(tuning)
	for k, v in pairs(tuning) do
		TUNING[k] = v
	end
end

local tuning_vars = {
	none = { 
		METEOR_SHOWER_LVL1_BASETIME = 0,
		METEOR_SHOWER_LVL1_VARTIME = 0,
		METEOR_SHOWER_LVL2_BASETIME = 0,
		METEOR_SHOWER_LVL2_VARTIME = 0,
		METEOR_SHOWER_LVL3_BASETIME = 0,
		METEOR_SHOWER_LVL3_VARTIME = 0,

		METEOR_SHOWER_LVL1_DURATION_BASE = 0,
		METEOR_SHOWER_LVL1_DURATIONVAR_MIN = 0,
		METEOR_SHOWER_LVL1_DURATIONVAR_MAX = 0,
		METEOR_SHOWER_LVL1_METEORSPERSEC_MIN = 0,
		METEOR_SHOWER_LVL1_METEORSPERSEC_MAX = 0,
		METEOR_SHOWER_LVL1_MEDMETEORS_MIN = 0,
		METEOR_SHOWER_LVL1_MEDMETEORS_MAX = 0,
		METEOR_SHOWER_LVL1_LRGMETEORS_MIN = 0,
		METEOR_SHOWER_LVL1_LRGMETEORS_MAX = 0,

		METEOR_SHOWER_LVL2_DURATION_BASE = 0,
		METEOR_SHOWER_LVL2_DURATIONVAR_MIN = 0,
		METEOR_SHOWER_LVL2_DURATIONVAR_MAX = 0,
		METEOR_SHOWER_LVL2_METEORSPERSEC_MIN = 0,
		METEOR_SHOWER_LVL2_METEORSPERSEC_MAX = 0,
		METEOR_SHOWER_LVL2_MEDMETEORS_MIN = 0,
		METEOR_SHOWER_LVL2_MEDMETEORS_MAX = 0,
		METEOR_SHOWER_LVL2_LRGMETEORS_MIN = 0,
		METEOR_SHOWER_LVL2_LRGMETEORS_MAX = 0,

		METEOR_SHOWER_LVL3_DURATION_BASE = 0,
		METEOR_SHOWER_LVL3_DURATIONVAR_MIN = 0,
		METEOR_SHOWER_LVL3_DURATIONVAR_MAX = 0,
		METEOR_SHOWER_LVL3_METEORSPERSEC_MIN = 0,
		METEOR_SHOWER_LVL3_METEORSPERSEC_MAX = 0,
		METEOR_SHOWER_LVL3_MEDMETEORS_MIN = 0,
		METEOR_SHOWER_LVL3_MEDMETEORS_MAX = 0,
		METEOR_SHOWER_LVL3_LRGMETEORS_MIN = 0,
		METEOR_SHOWER_LVL3_LRGMETEORS_MAX = 0, 
	},
	less = { 
		METEOR_SHOWER_LVL1_BASETIME = TUNING.TOTAL_DAY_TIME*12,
		METEOR_SHOWER_LVL1_VARTIME = TUNING.TOTAL_DAY_TIME*8,
		METEOR_SHOWER_LVL2_BASETIME = TUNING.TOTAL_DAY_TIME*18,
		METEOR_SHOWER_LVL2_VARTIME = TUNING.TOTAL_DAY_TIME*12,
		METEOR_SHOWER_LVL3_BASETIME = TUNING.TOTAL_DAY_TIME*24,
		METEOR_SHOWER_LVL3_VARTIME = TUNING.TOTAL_DAY_TIME*16,

		METEOR_SHOWER_LVL1_DURATION_BASE = 5,
		METEOR_SHOWER_LVL1_DURATIONVAR_MIN = 5,
		METEOR_SHOWER_LVL1_DURATIONVAR_MAX = 10,
		METEOR_SHOWER_LVL1_METEORSPERSEC_MIN = 2,
		METEOR_SHOWER_LVL1_METEORSPERSEC_MAX = 4,
		METEOR_SHOWER_LVL1_MEDMETEORS_MIN = 1,
		METEOR_SHOWER_LVL1_MEDMETEORS_MAX = 3,
		METEOR_SHOWER_LVL1_LRGMETEORS_MIN = 1,
		METEOR_SHOWER_LVL1_LRGMETEORS_MAX = 4,

		METEOR_SHOWER_LVL2_DURATION_BASE = 5,
		METEOR_SHOWER_LVL2_DURATIONVAR_MIN = 10,
		METEOR_SHOWER_LVL2_DURATIONVAR_MAX = 20,
		METEOR_SHOWER_LVL2_METEORSPERSEC_MIN = 3,
		METEOR_SHOWER_LVL2_METEORSPERSEC_MAX = 7,
		METEOR_SHOWER_LVL2_MEDMETEORS_MIN = 2,
		METEOR_SHOWER_LVL2_MEDMETEORS_MAX = 4,
		METEOR_SHOWER_LVL2_LRGMETEORS_MIN = 2,
		METEOR_SHOWER_LVL2_LRGMETEORS_MAX = 7,

		METEOR_SHOWER_LVL3_DURATION_BASE = 5,
		METEOR_SHOWER_LVL3_DURATIONVAR_MIN = 15,
		METEOR_SHOWER_LVL3_DURATIONVAR_MAX = 30,
		METEOR_SHOWER_LVL3_METEORSPERSEC_MIN = 4,
		METEOR_SHOWER_LVL3_METEORSPERSEC_MAX = 10,
		METEOR_SHOWER_LVL3_MEDMETEORS_MIN = 3,
		METEOR_SHOWER_LVL3_MEDMETEORS_MAX = 6,
		METEOR_SHOWER_LVL3_LRGMETEORS_MIN = 3,
		METEOR_SHOWER_LVL3_LRGMETEORS_MAX = 10, 
	},
	more = { 
		METEOR_SHOWER_LVL1_BASETIME = TUNING.TOTAL_DAY_TIME*3,
		METEOR_SHOWER_LVL1_VARTIME = TUNING.TOTAL_DAY_TIME*2,
		METEOR_SHOWER_LVL2_BASETIME = TUNING.TOTAL_DAY_TIME*5,
		METEOR_SHOWER_LVL2_VARTIME = TUNING.TOTAL_DAY_TIME*3,
		METEOR_SHOWER_LVL3_BASETIME = TUNING.TOTAL_DAY_TIME*6,
		METEOR_SHOWER_LVL3_VARTIME = TUNING.TOTAL_DAY_TIME*4,

		METEOR_SHOWER_LVL1_DURATION_BASE = 5,
		METEOR_SHOWER_LVL1_DURATIONVAR_MIN = 5,
		METEOR_SHOWER_LVL1_DURATIONVAR_MAX = 10,
		METEOR_SHOWER_LVL1_METEORSPERSEC_MIN = 2,
		METEOR_SHOWER_LVL1_METEORSPERSEC_MAX = 4,
		METEOR_SHOWER_LVL1_MEDMETEORS_MIN = 1,
		METEOR_SHOWER_LVL1_MEDMETEORS_MAX = 3,
		METEOR_SHOWER_LVL1_LRGMETEORS_MIN = 1,
		METEOR_SHOWER_LVL1_LRGMETEORS_MAX = 4,

		METEOR_SHOWER_LVL2_DURATION_BASE = 5,
		METEOR_SHOWER_LVL2_DURATIONVAR_MIN = 10,
		METEOR_SHOWER_LVL2_DURATIONVAR_MAX = 20,
		METEOR_SHOWER_LVL2_METEORSPERSEC_MIN = 3,
		METEOR_SHOWER_LVL2_METEORSPERSEC_MAX = 7,
		METEOR_SHOWER_LVL2_MEDMETEORS_MIN = 2,
		METEOR_SHOWER_LVL2_MEDMETEORS_MAX = 4,
		METEOR_SHOWER_LVL2_LRGMETEORS_MIN = 2,
		METEOR_SHOWER_LVL2_LRGMETEORS_MAX = 7,

		METEOR_SHOWER_LVL3_DURATION_BASE = 5,
		METEOR_SHOWER_LVL3_DURATIONVAR_MIN = 15,
		METEOR_SHOWER_LVL3_DURATIONVAR_MAX = 30,
		METEOR_SHOWER_LVL3_METEORSPERSEC_MIN = 4,
		METEOR_SHOWER_LVL3_METEORSPERSEC_MAX = 10,
		METEOR_SHOWER_LVL3_MEDMETEORS_MIN = 3,
		METEOR_SHOWER_LVL3_MEDMETEORS_MAX = 6,
		METEOR_SHOWER_LVL3_LRGMETEORS_MIN = 3,
		METEOR_SHOWER_LVL3_LRGMETEORS_MAX = 10, 
	},
	lots = { 
		METEOR_SHOWER_LVL1_BASETIME = TUNING.TOTAL_DAY_TIME*2,
		METEOR_SHOWER_LVL1_VARTIME = TUNING.TOTAL_DAY_TIME*1,
		METEOR_SHOWER_LVL2_BASETIME = TUNING.TOTAL_DAY_TIME*3,
		METEOR_SHOWER_LVL2_VARTIME = TUNING.TOTAL_DAY_TIME*2,
		METEOR_SHOWER_LVL3_BASETIME = TUNING.TOTAL_DAY_TIME*4,
		METEOR_SHOWER_LVL3_VARTIME = TUNING.TOTAL_DAY_TIME*2,

		METEOR_SHOWER_LVL1_DURATION_BASE = 5,
		METEOR_SHOWER_LVL1_DURATIONVAR_MIN = 5,
		METEOR_SHOWER_LVL1_DURATIONVAR_MAX = 10,
		METEOR_SHOWER_LVL1_METEORSPERSEC_MIN = 2,
		METEOR_SHOWER_LVL1_METEORSPERSEC_MAX = 4,
		METEOR_SHOWER_LVL1_MEDMETEORS_MIN = 1,
		METEOR_SHOWER_LVL1_MEDMETEORS_MAX = 3,
		METEOR_SHOWER_LVL1_LRGMETEORS_MIN = 1,
		METEOR_SHOWER_LVL1_LRGMETEORS_MAX = 4,

		METEOR_SHOWER_LVL2_DURATION_BASE = 5,
		METEOR_SHOWER_LVL2_DURATIONVAR_MIN = 10,
		METEOR_SHOWER_LVL2_DURATIONVAR_MAX = 20,
		METEOR_SHOWER_LVL2_METEORSPERSEC_MIN = 3,
		METEOR_SHOWER_LVL2_METEORSPERSEC_MAX = 7,
		METEOR_SHOWER_LVL2_MEDMETEORS_MIN = 2,
		METEOR_SHOWER_LVL2_MEDMETEORS_MAX = 4,
		METEOR_SHOWER_LVL2_LRGMETEORS_MIN = 2,
		METEOR_SHOWER_LVL2_LRGMETEORS_MAX = 7,

		METEOR_SHOWER_LVL3_DURATION_BASE = 5,
		METEOR_SHOWER_LVL3_DURATIONVAR_MIN = 15,
		METEOR_SHOWER_LVL3_DURATIONVAR_MAX = 30,
		METEOR_SHOWER_LVL3_METEORSPERSEC_MIN = 4,
		METEOR_SHOWER_LVL3_METEORSPERSEC_MAX = 10,
		METEOR_SHOWER_LVL3_MEDMETEORS_MIN = 3,
		METEOR_SHOWER_LVL3_MEDMETEORS_MAX = 6,
		METEOR_SHOWER_LVL3_LRGMETEORS_MIN = 3,
		METEOR_SHOWER_LVL3_LRGMETEORS_MAX = 10, 
	},
}

local difficulty = nil
if METEORSHOWERS == -2 then
	difficulty = "none"
elseif METEORSHOWERS == -1 then
	difficulty = "less"
elseif METEORSHOWERS == 1 then
	difficulty = "more"
elseif METEORSHOWERS == 2 then
	difficulty = "lots"
end

if difficulty then
	OverrideTuningVariables(tuning_vars[difficulty])
end