STRINGS.RECIPE_DESC.GRINDER = "Grind ALL the things!"
STRINGS.RECIPE_DESC.INK = "Write ALL the books!"
STRINGS.RECIPE_DESC.QUILL = "Write ALL the books!"
STRINGS.RECIPE_DESC.WRITINGDESK = "Write ALL the books!"
STRINGS.RECIPE_DESC.LINKPANEL = "Travel to new worlds!"
STRINGS.RECIPE_DESC.WORLDBOOK = "Write ALL the ages!"
STRINGS.RECIPE_DESC.LINKBOOK = "Link to ALL the ages!"

STRINGS.NAMES.GRINDER = "Mortar and Pestle"
STRINGS.NAMES.ACORN_GROUND = "Ground Birchnut"
STRINGS.NAMES.PINECONE_GROUND = "Ground Pinecone"
STRINGS.NAMES.COCONUT_GROUND = "Ground Coconut"
STRINGS.NAMES.GUMARABIC = "Gum Arabic"
STRINGS.NAMES.GUMARABIC_GROUND = "Ground Gum Arabic"
STRINGS.NAMES.INK = "Ink"
STRINGS.NAMES.QUILL = "Ink and Quill"
STRINGS.NAMES.WRITINGDESK = "Writing Desk"
STRINGS.NAMES.LINKPANEL = "Linking Panel"
STRINGS.NAMES.WORLDBOOK = "Descriptive Book"
STRINGS.NAMES.LINKBOOK = "Linking Book"
STRINGS.NAMES.SYMBOLSCROLL = "Ancient D'ni Scroll"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.GRINDER = "Grind ALL the things!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ACORN_GROUND = "I can use this to make ink!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PINECONE_GROUND = "I can use this to make ink!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.COCONUT_GROUND = "I can use this to make ink!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUMARABIC = "Chewy!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GUMARABIC_GROUND = "I can use this to make ink!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.INK = "I can use this to write books!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUILL = "I can use this to write books!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WRITINGDESK = "I can use this to write books!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LINKPANEL = "This panel will allow me to use my books to travel to other worlds!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WORLDBOOK = {
	GENERIC = "This book describes %s!",
	LINKED = "This book links to %s!"
}
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LINKBOOK = {
	GENERIC = "This book can take me to another world!",
	BROKEN = "This book's link has been broken!"
}
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SYMBOLSCROLL = "What secrets could this scroll contain?"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.SYMBOL_WAVES = "Splishy splashy!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SYMBOL_TASK = "With this I can move mountains!"

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_NOINK = "I need more ink to do that."
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_BADDIM = "I can't use that in this world."
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_LINKBROKEN = "This book's link has been broken!"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_WORLDBOOKFINISHED = "%s is finished! Now I can link to that world!"

if not STRINGS.PREFIXES then STRINGS.PREFIXES = {} end
STRINGS.PREFIXES.UNBOUND = "Unbound"
STRINGS.PREFIXES.BROKEN = "Broken"

if not STRINGS.MISC then STRINGS.MISC = {} end
STRINGS.MISC.LINKBOOK_CONJUNCTION = "to"
STRINGS.MISC.UNKNOWN_LINK = "an unknown age"
STRINGS.MISC.LINK_SURVIVAL = "the Starting Age"
STRINGS.MISC.LINK_TROPICS = "the Starting Age"
STRINGS.MISC.LINK_FOREST = "a Forest Age"
STRINGS.MISC.LINK_CAVE = "a Cave Age"
STRINGS.MISC.LINK_TROPICS = "a Tropical Age"
STRINGS.MISC.NEW_WORLDBOOK = "New Age"

STRINGS.UI.LOADGAMESCREEN.AGE = "Myst Age"

STRINGS.UI.WRITE = "Write"
STRINGS.UI.GRIND = "Grind"
STRINGS.UI.CONFIRM = "Confirm"

if not STRINGS.UI.PROTOTYPER_HINTS then STRINGS.UI.PROTOTYPER_HINTS = {} end
STRINGS.UI.PROTOTYPER_HINTS.MYST_2 = "Use a Writing Desk to build a prototype!"

STRINGS.TEMPLATES = {
	WORLDBOOK = {
		NAME = "Name",
		TYPE = "World Type"
	}
}