TUNING.PROTOTYPER_TREES.WRITINGDESK = {
	SCIENCE = 0,
	MAGIC = 0,
	ANCIENT = 0,
	OBSIDIAN = 0,
	MYST = 2
}

TUNING.QUILL_USES = 10
TUNING.GRINDER_USES = 5

TUNING.LINKBOOK_COST = 5
TUNING.WORLDBOOK_COST = 7.5